```{r}
library(readxl)
library(tidyverse)
library(dplyr)
library(tseries)
library(vars)
library(lmtest)
library(urca)
library(tsDyn)
library(ggplot2)
library(dynlm)
library(openxlsx)
library(writexl)
```

```{r}
#Load data and drop missing values
NWT <- read_excel("Data/All_data.xlsx", sheet = "annual data - NWT") %>% drop_na()
Nunavut <- read_excel("Data/All_data.xlsx", sheet = "annual data - Nunavut") %>% drop_na()
```

```{r}
#Load variables
nwt_gdp_per_capita <- ts(NWT$GDP_per_capita,start = 1997, frequency = 1)
nwt_yellowknife <- ts(NWT$air_movement_yellowknife, start = 1997, frequency = 1) 
nwt_inuvik <- ts(NWT$air_movement_inuvik, start = 1997, frequency = 1)
nu_gdp_per_capita <- ts(Nunavut$GDP_per_capita, start = 1999, frequency = 1)
nu_iqaluit <- ts(Nunavut$air_movements_Iqaluit, start = 1999, frequency = 1)
nu_rankin_inlet <- ts(Nunavut$air_movements_Rankin_Inlet, start = 1999, frequency = 1)
```

```{r}
nwt_gdp_per_capita_log <- ts(log(nwt_gdp_per_capita), start = 1997, frequency = 1)
nu_gdp_per_capita_log <- ts(log(nu_gdp_per_capita), start = 1999, frequency = 1)
nwt_inuvik_log <- ts(log(nwt_inuvik), start = 1997, frequency = 1)
nwt_yellowknife_log <- ts(log(nwt_yellowknife), start = 1997, frequency = 1)
nu_iqaluit_log <- ts(log(nu_iqaluit), start = 1999, frequency = 1)
nu_rankin_inlet_log <- ts(log(nu_rankin_inlet), start = 1999, frequency = 1)
```

#Plots
```{r}
plot_vars <- function(var1,air,title){
  plot(var1, type = 'l', col = 'red',xlab = '', ylab = '', ylim = range(var1))
  par(new = TRUE)
  plot(air, type = 'l', axes = FALSE, col = 'black', xlab = '', ylab = '', ylim = range(air))
  axis(side = 4)
  legend("topleft", legend = c("GDP per capita", "Aircraft movements"), col =  c("red","black"), lty=1, cex = 0.8)
  title(title, line = 1)
}
```

```{r}
# GDP per capita plot
plot(nwt_gdp_per_capita, type = "l", ylim = c(40000, 125000), col = "blue", lwd = 2, 
     ylab = "GDP per capita", main = "NWT VS. Nunavut")
lines(nu_gdp_per_capita, col = "red", lwd = 2)
legend("topright", legend = c("NWT", "Nunavut"), col = c("blue", "red"), lty = 1, lwd = 2)
```

#Step 1: Unit root test
```{r}
ur_test <- function(data){
  adf_test <- ur.df(data, type = "drift", selectlags = "AIC")
  summary(adf_test)
}
```

```{r}
ur_test(nu_rankin_inlet_log)
```

# Step 2: Cointegration test
```{r}
# Engle-Granger two-step test
EG_test <- function(x,y){
  reg <- lm(y~x)
  plot(resid(reg))
  z_hat <- resid(reg)
  var_name_x <- deparse(substitute(x))
  var_name_y <- deparse(substitute(y))
  cat("X =", var_name_x,",", "Y =", var_name_y, "\n")
  print(summary(ur.df(z_hat, type = "none", selectlags = "AIC")))
}
```

```{r}
EG_test(nu_rankin_inlet_log, nu_gdp_per_capita_log)
```

# Step 3: Model set up
```{r}
# Select the number of lags in VAR
lag_select <- function(x,y,p){
  result <- VARselect(cbind(x,y), lag.max = p, type = 'const',
                      season = NULL, exogen = NULL)
  print(result)
}
```

```{r}
# VECM model
vecm <- function(x,y,p){
  ols <- dynlm(y~x)
  ect <- resid(ols)
  model <- summary(dynlm(d(y) ~ L(ect) + L(d(y),1:p) + L(d(x), 1:p)))
  coefs <- as.data.frame(model$coefficient)
  result_df <- cbind(coefs)

  print(model)
  return(result_df)
}
```

```{r}
# Yellowknife
print("AIRM >>> GDPPC")
yn_to_gdp <- vecm(nwt_yellowknife_log, nwt_gdp_per_capita_log,2)

print("GDPPC >>> AIRM")
gdp__to_yn <- vecm(nwt_gdp_per_capita_log,nwt_yellowknife_log,2)
```

```{r}
# Inuvik
print("AIRM >>> GDPPC")
inu_to_gdp <- vecm(nwt_inuvik_log,nwt_gdp_per_capita_log,2)

print("GDPPC >>> AIRM")
gdp_to_inu <- vecm(nwt_gdp_per_capita_log,nwt_inuvik_log,2)
```

```{r}
# Iqaluit
print("AIRM >>> GDPPC")
iqa_to_gdp <- vecm(nu_iqaluit_log, nu_gdp_per_capita_log,2)

print("GDPPC >>> AIRM")
gdp_to_iqa <- vecm(nu_gdp_per_capita_log,nu_iqaluit_log,2)
```

```{r}
# Rankin-Inlet
print("AIRM >>> GDPPC")
rank_to_gdp <- vecm(nu_rankin_inlet_log, nu_gdp_per_capita_log,1)

print("GDPPC >>> AIRM")
gdp_to_rank <- vecm(nu_gdp_per_capita_log,nu_rankin_inlet_log,1)
```

```{r}
#VAR model
var <- function(x,y,p){
  x_stat <- diff(x)
  y_stat <- diff(y)
  var_model <- VAR(cbind(x_stat,y_stat), p = p, type = "const")
  print(summary(var_model))
  result_df <- as.data.frame(coef(var_model))
  return (result_df)
}
```

# Step 4: model comparison (Wald test)
```{r}
# Short-run causality
wald_test_sr <- function(x,y,p){
  ols <- dynlm(y~x)
  ect <- resid(ols)
  unrestricted <- dynlm(d(y) ~ L(ect) + L(d(y), 1:p) + L(d(x), 1:p))
  restricted <- dynlm(d(y) ~ L(ect) + L(d(y), 1:p))
  waldtest(restricted, unrestricted, test = "Chisq")
}
```

```{r}
#Overall Granger causality
wald_test_lr <- function(x,y,p){
  ols <- dynlm(y~x)
  ect <- resid(ols)
  unrestricted <- dynlm(d(y) ~ L(ect) + L(d(y), 1:p) + L(d(x), 1:p))
  restricted <- dynlm(d(y) ~ L(d(y), 1:p))
  waldtest(restricted, unrestricted, test = "Chisq")
}
```

# Export VECM coefficients
```{r}
list_of_dfs <- list(yn_to_gdp,gdp__to_yn,inu_to_gdp,gdp_to_inu,
                    iqa_to_gdp,gdp_to_iqa,rank_to_gdp,gdp_to_rank)

write_xlsx(list_of_dfs, path = "VARs.xlsx")
```